require('knight.lsp')
require('knight.dotnet')
require('knight.treesitter')
require('knight.telescope')
require('knight.mappings')
require('knight.spelling')
require('knight.statusline')
require('knight.text')
